# Generated by Django 2.0 on 2018-01-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180125_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes',
        ),
    ]
